version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: changeme
    container_name: udy_elasticsearch
    networks:
      - elastic

  logstash:
    container_name: udy_logstash
    build:
      context: logstash/
    #volumes:
    #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #  - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elastic
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    container_name: udy_kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elastic
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
      - logstash

networks:
  elastic:
    driver: bridge